#!/usr/bin/env python3
"""sync_nets.py — pull nets from the schematic into the PCB.

KiCad expects every PCB to declare its nets at the top level:
    (net 0 "")
    (net 1 "GND")
    (net 2 "+3V3")
    ...
and every pad's net to reference both code and name:
    (pad "1" smd ... (net 2 "+3V3") ...)

The autogenerated PCB in this project has none of those declarations and
pads use a (net "name") form with no code. KiCad treats every pad as
disconnected as a result.

This tool:
  1. Runs `kicad-cli sch export netlist --format kicadsexpr` to get the
     authoritative net list (95 nets) from the schematic.
  2. Parses (net (code N) (name X) (node (ref R) (pin P)) ...).
  3. Inserts `(net N "name")` blocks at the PCB top level, right after
     `(general)` / `(layers)`.
  4. Rewrites every pad's `(net ...)` line to the full `(net N "name")`
     form, looking up by (refdes, pin) → net.
"""
from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PCB = REPO / "defcon_badge" / "defcon_badge.kicad_pcb"
SCH = REPO / "defcon_badge" / "defcon_badge.kicad_sch"
NETLIST = Path("/tmp/defcon_netlist.net")


def export_netlist() -> None:
    subprocess.run(
        ["kicad-cli", "sch", "export", "netlist", "--format", "kicadsexpr",
         "--output", str(NETLIST), str(SCH)],
        check=True, capture_output=True,
    )


def parse_netlist(text: str):
    """Return: nets = [(code:int, name:str)], pad_to_net = {(ref, pin): (code, name)}"""
    nets = []
    pad_to_net = {}
    # Each (net (code "N") (name "X") (node (ref "R") (pin "P") ...) ...)
    net_blocks = re.findall(
        r'\(net\s+\(code "(\d+)"\)\s+\(name "([^"]+)"\)\s+\(class "[^"]*"\)(.*?)\n\t\t\)',
        text, re.DOTALL,
    )
    for code, name, body in net_blocks:
        code = int(code)
        nets.append((code, name))
        for nm in re.finditer(r'\(node\s+\(ref "([^"]+)"\)\s+\(pin "([^"]+)"\)', body):
            pad_to_net[(nm.group(1), nm.group(2))] = (code, name)
    return nets, pad_to_net


def main() -> int:
    print("Exporting netlist...")
    export_netlist()
    nets, pad_to_net = parse_netlist(NETLIST.read_text())
    print(f"  {len(nets)} nets, {len(pad_to_net)} pad assignments")

    text = PCB.read_text()
    shutil.copy2(PCB, PCB.with_suffix(PCB.suffix + ".pre_netsync_backup"))

    # 1) Insert (net N "name") declarations after the (setup ...) block.
    # KiCad strips nets that come before (setup) on save, so order matters.
    # First strip any pre-existing (net N "name") declarations we may have added before.
    text = re.sub(r'\n\t\(net \d+ "[^"]*"\)', '', text)
    setup_start = text.index("\t(setup")
    depth = 0
    i = setup_start
    while i < len(text):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                layers_end = i + 1
                break
        i += 1
    # Build net declarations
    net_decls = "\n" + "\t(net 0 \"\")\n"
    for code, name in sorted(nets):
        net_decls += f'\t(net {code} "{name}")\n'

    text = text[:layers_end] + net_decls + text[layers_end:]

    # 2) Rewrite each pad's (net ...) line.
    # Footprint reference is in (property "Reference" "REF")
    # Pad has (pad "N" ... (net "name") ...) — replace with (net code "name").
    # Strategy: split by footprint, within each footprint, get the refdes,
    # then for each pad, look up by (refdes, pin number).
    chunks = re.split(r'(\n\t\(footprint )', text)
    out = [chunks[0]]
    i = 1
    rewritten = 0
    while i < len(chunks):
        delim = chunks[i]
        body = chunks[i + 1] if i + 1 < len(chunks) else ""
        m_ref = re.search(r'\(property "Reference" "([^"]+)"', body)
        refdes = m_ref.group(1) if m_ref else None

        if refdes:
            def replace_pad(m):
                nonlocal rewritten
                pad_block = m.group(0)
                pad_num_m = re.match(r'\(pad "([^"]+)"', pad_block)
                pad_num = pad_num_m.group(1) if pad_num_m else None
                if pad_num and (refdes, pad_num) in pad_to_net:
                    code, net_name = pad_to_net[(refdes, pad_num)]
                    new_block = re.sub(
                        r'\(net "[^"]*"\)',
                        f'(net {code} "{net_name}")',
                        pad_block,
                        count=1,
                    )
                    if new_block != pad_block:
                        rewritten += 1
                    return new_block
                # If we don't have a mapping but pad already has (net "X"),
                # leave it alone — KiCad will skip it as a no-net pad.
                return pad_block

            # Match a pad block: (pad "N" ... ) — multi-line, can have nested
            # () so we need a balanced matcher. Easier: match (pad ... (uuid "..."))
            # since pads end with (uuid ...).
            body = re.sub(
                r'\(pad "[^"]+" [^)]*?\([^)]*?\)(?:[^)]*?\([^)]*?\))*?[^)]*?\(uuid "[^"]+"\)\s*\)',
                replace_pad,
                body,
                flags=re.DOTALL,
            )

        out.append(delim)
        out.append(body)
        i += 2

    new_text = "".join(out)
    PCB.write_text(new_text)
    print(f"  rewrote {rewritten} pad nets")
    return 0


if __name__ == "__main__":
    sys.exit(main())
